
---
output: md_document
---

```{r echo=FALSE, output=FALSE, eval=FALSE}
## This is just to build a small example to output to a .md
## file and then paste to README.md
## the following may help to set pandoc version
## Sys.setenv(PATH=paste0("/opt/software/pandoc/bin:", Sys.getenv("PATH")))
```


```{r echo=FALSE, output=FALSE, message=FALSE}
library(knitr) ## kable
opts_chunk$set(comment=NA)
##opts_chunk$set(echo=FALSE)
##opts_chunk$set(dev = 'pdf')
##opts_chunk$set(fig.height=7)
##opts_chunk$set(fig.align="center")
```

Repository creation:

```{r}
library(repo)
rp <- repo_open(tempdir(), T)
rp$options(replace=T)
```

Putting some stuff in (saved on permanent storage):

```{r}
rp$put(Inf, "God", "This variable contains the Creator", c("tag1"))
rp$put(0, "user", "This variable contains a user", c("tag1"))
```
Putting with dependencies set:

```{r}
rp$put(pi, "The Pi costant",
    "This is just a variable containing the Pi costant", c("tag1"), depends="God")

rp$put(1:10, "r", "10 different radius lengths", c("tag1"), depends="user")
```

Getting stuff from the repository on the fly:

```{r}
diam <- 2 * rp$get("r")
circum <- 2 * rp$get("The Pi costant") * rp$get("r")
area <- rp$get("The Pi costant") * rp$get("r") ^ 2

rp$put(diam, "diameter", "This is the diameter", c("tag1"), depends = "r")
rp$put(circum, "circumference", "This is the circumference", c("tag1"), depends = c("The Pi costant", "r"))
rp$put(area, "area", "This is the area", c("tag1"), depends = c("The Pi costant", "r"))
```
The results:
```{r}
rp$get("diameter")
rp$get("circumference")
rp$get("area")
```
Repository contents:

```{r}
print(rp)
rp$info()
```
Visualizing dependencies:

```{r}
rp$dependencies()
```
